### ISSUE TITLE
Failed to load the js2coffee package

### ISSUE THREAD

**Issue by vinodpanicker** [jdcrensh/atom-js2coffee#19]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Ubuntu 14.04.3
**Thrown From**: [js2coffee](https://github.com/Chandler/atom-js2coffee) package, v0.15.0

### Stack Trace

Failed to load the js2coffee package

```
At Identifier 'END' has already been declared

TypeError: Identifier 'END' has already been declared
  at evalmachine.<anonymous>:1:1
  at Object.exports.runInThisContext (vm.js:54:17)
  at global.eval (/home/toolsdev/.atom/packages/js2coffee/node_modules/loophole/lib/loophole.js:12:19)
  at /home/toolsdev/.atom/packages/js2coffee/node_modules/js2coffee/out/lib/narcissus_packed.js:894:5
  at Object.<anonymous> (/home/toolsdev/.atom/packages/js2coffee/node_modules/js2coffee/out/lib/narcissus_packed.js:2274:2)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/home/toolsdev/.atom/packages/js2coffee/node_modules/js2coffee/out/lib/js2coffee.js:11:12)
  at Object.<anonymous> (/home/toolsdev/.atom/packages/js2coffee/node_modules/js2coffee/out/lib/js2coffee.js:1144:4)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at /home/toolsdev/.atom/packages/js2coffee/lib/js2coffee.coffee:2:32
  at exports.allowUnsafeEval (/home/toolsdev/.atom/packages/js2coffee/node_modules/loophole/lib/loophole.js:14:14)
  at Object.<anonymous> (/home/toolsdev/.atom/packages/js2coffee/lib/js2coffee.coffee:2:13)
  at Object.<anonymous> (/home/toolsdev/.atom/packages/js2coffee/lib/js2coffee.coffee:1:1)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:663:34)
  at /usr/share/atom/resources/app.asar/src/package.js:115:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:438:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:390:14)
  at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:682:21)
  at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
  at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
  at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "autocomplete-php",
      "language-gfm",
      "language-gfm"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-symfony2, v0.2.1
autocomplete-go, v0.1.1
build-gradle, v0.6.0
coffee-refactor, v0.7.0
drupal, v1.8.0
environment, v1.1.1
go-config, v0.3.1
java-importer, v1.4.1
js-refactor, v0.6.0
js2coffee, v0.15.0
language-groovy-cloned-from-java, v0.3.0
language-markdown, v0.7.1
php-extract-method, v0.2.1
php-introspector, v1.0.0
refactor, v0.6.0

# Dev
No dev packages
```

**Comment by jdcrensh** [comment]
Duplicates #4
