### ISSUE TITLE
Failed to activate the js2coffee package

### ISSUE THREAD

**Issue by fungilation** [jdcrensh/atom-js2coffee#8]
[Enter steps to reproduce below:]

1. Highlight chunk of coffeescript
2. Activate js2coffee

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [js2coffee](https://github.com/Chandler/atom-js2coffee) package, v0.15.0

### Stack Trace

Failed to activate the js2coffee package

```
At evalmachine.<anonymous>:1
const END = 0, NEWLINE = 1, SEMICOLON = 2, COMMA = 3, ASSIGN = 4, HOOK = 5, CO
^
Identifier 'END' has already been declared

evalmachine.<anonymous>:1
const END = 0, NEWLINE = 1, SEMICOLON = 2, COMMA = 3, ASSIGN = 4, HOOK = 5, CO
^
TypeError: Identifier 'END' has already been declared
  at evalmachine.<anonymous>:1:1
  at Object.exports.runInThisContext (vm.js:76:17)
  at global.eval (~/.atom/packages/js2coffee/node_modules/loophole/lib/loophole.js:12:19)
  at ~/.atom/packages/js2coffee/node_modules/js2coffee/out/lib/narcissus_packed.js:894:5
  at Object.<anonymous> (~/.atom/packages/js2coffee/node_modules/js2coffee/out/lib/narcissus_packed.js:2274:2)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (~/.atom/packages/js2coffee/node_modules/js2coffee/out/lib/js2coffee.js:11:12)
  at Object.<anonymous> (~/.atom/packages/js2coffee/node_modules/js2coffee/out/lib/js2coffee.js:1144:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at ~/.atom/packages/js2coffee/lib/js2coffee.coffee:2:32
  at exports.allowUnsafeEval (~/.atom/packages/js2coffee/node_modules/loophole/lib/loophole.js:14:14)
  at Object.<anonymous> (~/.atom/packages/js2coffee/lib/js2coffee.coffee:2:13)
  at Object.<anonymous> (~/.atom/packages/js2coffee/lib/js2coffee.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:672:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:742:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:227:20)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -3:16.7 find-and-replace:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:16.5 core:paste (atom-text-editor.editor.mini)
  9x -3:15.9 find-and-replace:find-next (atom-text-editor.editor.mini)
     -3:11.9 find-and-replace:show (atom-text-editor.editor)
     -3:10.5 core:confirm (atom-text-editor.editor.mini)
     -3:06.7 core:close (atom-text-editor.editor.mini)
     -1:37.5 settings-view:open (atom-text-editor.editor.is-focused)
     -0:05.1 js2coffee:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".gitignore"
    ],
    "disabledPackages": [
      "metrics",
      "wrap-guide",
      "autosave",
      "htmlhint",
      "autoclose-html",
      "atom-handlebars",
      "font-awesome-snippetset",
      "underscorejs-snippets",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "minimap-selection",
      "emmet",
      "minimap",
      "angularjs",
      "autocomplete"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "projectHome": "~/Documents/code"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.22.3
atom-color-highlight, v3.0.8
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
autocomplete-snippets, v1.2.0
bezier-curve-editor, v0.6.6
close-after-last-tab, v0.1.5
color-picker, v1.4.4
html-entities, v0.3.1
javascript-snippets, v1.0.0
js2coffee, v0.15.0
language-jade, v0.3.0
language-spacebars, v0.2.2
linter, v0.12.0
linter-coffeelint, v0.2.0
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-shellcheck, v0.0.7
meteor-api, v2.12.0
script, v2.18.0
tabs-to-spaces, v0.9.0
tabular, v0.1.0

# Dev
No dev packages
```

**Comment by camel-chased** [comment]
i have the same

**Comment by jetpackjarrett** [comment]
:+1: happening for me too

**Comment by jdcrensh** [comment]
Duplicates #4
